import {
  BarChart3,
  BookOpen,
  Building2,
  File,
  FileQuestion,
  Files,
  Home,
  MonitorCogIcon,
  Settings,
  Ticket,
  User2,
  UserPlus2,
  Users2,
  Users2Icon,
} from "lucide-react";

export const menus = [{
    label: "Bosh sahifa",
    href: "/dashboard",
    icon: Home,
    roles: ["OWNER", "CENTER_ADMIN", "TEACHER", "STUDENT"],
    is_mobile: true,
  },
  {
    label: "Markazlar",
    href: "/dashboard/centers",
    icon: Building2,
    roles: ["OWNER"],
    is_mobile: true,
  },
  {
    label: "So'rovlar",
    href: "/dashboard/requests",
    icon: UserPlus2,
    roles: ["OWNER"],
    is_mobile: true,
  },
  {
    label: "Monitiring",
    href: "/dashboard/monitoring",
    icon: MonitorCogIcon,
    roles: ["OWNER"],
    is_mobile: true,
  },
  // {
  //   label: "Obunalar",
  //   href: "/dashboard/subscriptions",
  //   icon: CircleDollarSign,
  //   roles: ["OWNER"],
  //   is_mobile: true,
  // },
  {
    label: "Taklif kodlari",
    href: "/dashboard/invitations",
    icon: Ticket,
    roles: ["CENTER_ADMIN"],
  },
  {
    label: "user_title",
    href: "/dashboard/users",
    icon: Users2,
    roles: ["CENTER_ADMIN"],
  },
  {
    label: "groups_title",
    href: "/dashboard/groups",
    icon: Users2Icon,
    roles: ["CENTER_ADMIN"],
  },
  {
    label: "materials_title",
    href: "/dashboard/materials/folders",
    icon: Files,
    roles: ["CENTER_ADMIN", "TEACHER", "STUDENT"],
  },
  {
    label: "mock_title",
    href: "/dashboard/mocks",
    icon: BookOpen,
    roles: ["TEACHER", "CENTER_ADMIN"],
    is_mobile: true
  },
  {
    label: "Assignments",
    href: "/dashboard/assignments/exam",
    icon: File,
    roles: ["TEACHER", "CENTER_ADMIN", "STUDENT"],
    is_mobile: true,
  },
  {
    label: "flashcards_title",
    href: "/dashboard/flashcards",
    icon: FileQuestion,
    roles: ["STUDENT", "OWNER", "CENTER_ADMIN", "TEACHER"],
    is_mobile: true,
  },
  {
    label: "Profil",
    href: "/dashboard/profile",
    icon: User2,
    roles: ["OWNER", "CENTER_ADMIN", "TEACHER", "STUDENT"],
    is_mobile: true,
  },
];